// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwouXQZjcKBZ9cpqyFpgLX2gteXkbYTC0',
    appId: '1:337839342021:web:52406cb6303b167846cbac',
    messagingSenderId: '337839342021',
    projectId: 'wallpaper-6f9a7',
    authDomain: 'wallpaper-6f9a7.firebaseapp.com',
    databaseURL: 'https://wallpaper-6f9a7-default-rtdb.firebaseio.com',
    storageBucket: 'wallpaper-6f9a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPQfP823FJA5fL6NYBQjz2bE2eEivzwro',
    appId: '1:337839342021:android:4e6cc31713bc75b846cbac',
    messagingSenderId: '337839342021',
    projectId: 'wallpaper-6f9a7',
    databaseURL: 'https://wallpaper-6f9a7-default-rtdb.firebaseio.com',
    storageBucket: 'wallpaper-6f9a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7HnT_6fliz2T-Pazc-Xju3wByvg7Dvt4',
    appId: '1:337839342021:ios:d1383195d106de5d46cbac',
    messagingSenderId: '337839342021',
    projectId: 'wallpaper-6f9a7',
    databaseURL: 'https://wallpaper-6f9a7-default-rtdb.firebaseio.com',
    storageBucket: 'wallpaper-6f9a7.appspot.com',
    androidClientId: '337839342021-0t6lpnq2hufipbo04g0ri7saeogvdsdm.apps.googleusercontent.com',
    iosClientId: '337839342021-62nmr99n2lnq50sp1ets0n51m0dmvero.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7HnT_6fliz2T-Pazc-Xju3wByvg7Dvt4',
    appId: '1:337839342021:ios:d1383195d106de5d46cbac',
    messagingSenderId: '337839342021',
    projectId: 'wallpaper-6f9a7',
    databaseURL: 'https://wallpaper-6f9a7-default-rtdb.firebaseio.com',
    storageBucket: 'wallpaper-6f9a7.appspot.com',
    androidClientId: '337839342021-0t6lpnq2hufipbo04g0ri7saeogvdsdm.apps.googleusercontent.com',
    iosClientId: '337839342021-62nmr99n2lnq50sp1ets0n51m0dmvero.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVrj6CK5oOHSFG8Yfojd-P2g-iF2WrLiU',
    appId: '1:337839342021:web:e12cc731f2620e5446cbac',
    messagingSenderId: '337839342021',
    projectId: 'wallpaper-6f9a7',
    authDomain: 'wallpaper-6f9a7.firebaseapp.com',
    databaseURL: 'https://wallpaper-6f9a7-default-rtdb.firebaseio.com',
    storageBucket: 'wallpaper-6f9a7.appspot.com',
  );
}
